# Generated by Django 4.1.5 on 2023-02-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_feedback_feedback_feedback1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='upload',
            new_name='booking',
        ),
    ]
